name: preferences
description: Create Preference Screens easily with advanced features and subpages
version: 5.3.0+1
homepage: https://gitlab.com/redsolver/preferences

environment:
  # sdk: ">=2.0.0 <3.0.0"
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # shared_preferences: '>=0.5.2 <2.0.0'
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
